### ISSUE TITLE
Add claim to Access Token?

### ISSUE THREAD

**Issue by mitni455** [r3dlin3/phpOIDC#7]
How do I add a claim to an Access Token?

**Comment by r3dlin3** [comment]
At this moment, the generated access token is not a JWT token. It is a random string. For instance: `3olehZIqZOaTuXvt6hAfC_oFN2G8r54W-NmRaQm8j0d`.

The ID Token is a JWT obviously and contains the following claims:
```
{
  "iss": "http://localhost:8001/phpOp",
  "sub": "a.b@example.com",
  "aud": [
    "clientId"
  ],
  "exp": 1598470071,
  "iat": 1598469771,
  "nonce": "49cd37475ac3481b81dd244750061a3d",
  "at_hash": "xk15kGFvAErycUgE6Ykq2g"
}
```

All claims of the user can be fetched from the Userinfo endpoint, depending on the requested scope.

**Comment by mitni455** [comment]
Ah cool gotcha 

Opaque tokens only 

No worries I'll add once myself by copying the id token generation pattern. Thank you.
